version: "3.9"

volumes:
  mysql:
  redis:
  db:

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_SERVE_STATIC_FILES: 'true'
      MYSQL_HOST: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      REDIS_URL: "redis://redis:6379/1"
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
